<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>shadcnui</AssemblyName>
        <RootNamespace>shadcnui</RootNamespace>
        <TargetFramework>netstandard2.1</TargetFramework>
        <LangVersion>10.0</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Configurations>IL2CPP_MELONLOADER_PRE57;IL2CPP_MELONLOADER;IL2CPP_BEPINEX;Mono_Melonloader;Mono_BepInEx</Configurations>
        <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
        <NoWarn>$(NoWarn);MSB3270;MSB3277</NoWarn>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'IL2CPP_MELONLOADER_PRE57|AnyCPU' ">
        <DebugType>pdbonly</DebugType>
        <Optimize>true</Optimize>
        <OutputPath>bin\IL2CPP_MELONLOADER_PRE57\</OutputPath>
        <DefineConstants>TRACE;IL2CPP_MELONLOADER_PRE57</DefineConstants>
        <ErrorReport>prompt</ErrorReport>
        <WarningLevel>4</WarningLevel>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'IL2CPP_MELONLOADER|AnyCPU' ">
        <DebugType>pdbonly</DebugType>
        <Optimize>true</Optimize>
        <OutputPath>bin\IL2CPP_MELONLOADER\</OutputPath>
        <DefineConstants>TRACE;IL2CPP_MELONLOADER</DefineConstants>
        <ErrorReport>prompt</ErrorReport>
        <WarningLevel>4</WarningLevel>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'IL2CPP_BEPINEX|AnyCPU' ">
        <DebugType>pdbonly</DebugType>
        <Optimize>true</Optimize>
        <OutputPath>bin\IL2CPP_BEPINEX\</OutputPath>
        <DefineConstants>TRACE;IL2CPP_BEPINEX</DefineConstants>
        <ErrorReport>prompt</ErrorReport>
        <WarningLevel>4</WarningLevel>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Mono_Melonloader|AnyCPU' ">
        <DebugType>pdbonly</DebugType>
        <Optimize>true</Optimize>
        <OutputPath>bin\Mono_Melonloader\</OutputPath>
        <DefineConstants>TRACE;MONO_MELONLOADER</DefineConstants>
        <ErrorReport>prompt</ErrorReport>
        <WarningLevel>4</WarningLevel>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Mono_BepInEx|AnyCPU' ">
        <DebugType>pdbonly</DebugType>
        <Optimize>true</Optimize>
        <OutputPath>bin\Mono_BepInEx\</OutputPath>
        <DefineConstants>TRACE;MONO_BEPINEX</DefineConstants>
        <ErrorReport>prompt</ErrorReport>
        <WarningLevel>4</WarningLevel>
    </PropertyGroup>
    <ItemGroup>
        <None Remove="Directory.Build.props" />
        <None Remove="Directory.Build.targets" />
    </ItemGroup>
    <ItemGroup>
        <Reference Include="UnityEngine">
            <HintPath>$(ReferencePath)UnityEngine.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.AccessibilityModule">
            <HintPath>$(ReferencePath)UnityEngine.AccessibilityModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.AIModule">
            <HintPath>$(ReferencePath)UnityEngine.AIModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.AndroidJNIModule">
            <HintPath>$(ReferencePath)UnityEngine.AndroidJNIModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.AnimationModule">
            <HintPath>$(ReferencePath)UnityEngine.AnimationModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.AssetBundleModule">
            <HintPath>$(ReferencePath)UnityEngine.AssetBundleModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.AudioModule">
            <HintPath>$(ReferencePath)UnityEngine.AudioModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.ClothModule">
            <HintPath>$(ReferencePath)UnityEngine.ClothModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.ContentLoadModule">
            <HintPath>$(ReferencePath)UnityEngine.ContentLoadModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.CoreModule">
            <HintPath>$(ReferencePath)UnityEngine.CoreModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.CrashReportingModule">
            <HintPath>$(ReferencePath)UnityEngine.CrashReportingModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.DirectorModule">
            <HintPath>$(ReferencePath)UnityEngine.DirectorModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.DSPGraphModule">
            <HintPath>$(ReferencePath)UnityEngine.DSPGraphModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.GameCenterModule">
            <HintPath>$(ReferencePath)UnityEngine.GameCenterModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.GIModule">
            <HintPath>$(ReferencePath)UnityEngine.GIModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.GridModule">
            <HintPath>$(ReferencePath)UnityEngine.GridModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.HierarchyCoreModule">
            <HintPath>$(ReferencePath)UnityEngine.HierarchyCoreModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.HotReloadModule">
            <HintPath>$(ReferencePath)UnityEngine.HotReloadModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.ImageConversionModule">
            <HintPath>$(ReferencePath)UnityEngine.ImageConversionModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.IMGUIModule">
            <HintPath>$(ReferencePath)UnityEngine.IMGUIModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.InputForUIModule">
            <HintPath>$(ReferencePath)UnityEngine.InputForUIModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.InputLegacyModule">
            <HintPath>$(ReferencePath)UnityEngine.InputLegacyModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.InputModule">
            <HintPath>$(ReferencePath)UnityEngine.InputModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.JSONSerializeModule">
            <HintPath>$(ReferencePath)UnityEngine.JSONSerializeModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.LocalizationModule">
            <HintPath>$(ReferencePath)UnityEngine.LocalizationModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.MarshallingModule">
            <HintPath>$(ReferencePath)UnityEngine.MarshallingModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.MultiplayerModule">
            <HintPath>$(ReferencePath)UnityEngine.MultiplayerModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.ParticleSystemModule">
            <HintPath>$(ReferencePath)UnityEngine.ParticleSystemModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.PerformanceReportingModule">
            <HintPath>$(ReferencePath)UnityEngine.PerformanceReportingModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.Physics2DModule">
            <HintPath>$(ReferencePath)UnityEngine.Physics2DModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.PhysicsModule">
            <HintPath>$(ReferencePath)UnityEngine.PhysicsModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.PropertiesModule">
            <HintPath>$(ReferencePath)UnityEngine.PropertiesModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule">
            <HintPath>$(ReferencePath)UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.ScreenCaptureModule">
            <HintPath>$(ReferencePath)UnityEngine.ScreenCaptureModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.SharedInternalsModule">
            <HintPath>$(ReferencePath)UnityEngine.SharedInternalsModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.SpriteMaskModule">
            <HintPath>$(ReferencePath)UnityEngine.SpriteMaskModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.SpriteShapeModule">
            <HintPath>$(ReferencePath)UnityEngine.SpriteShapeModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.StreamingModule">
            <HintPath>$(ReferencePath)UnityEngine.StreamingModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.SubstanceModule">
            <HintPath>$(ReferencePath)UnityEngine.SubstanceModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.SubsystemsModule">
            <HintPath>$(ReferencePath)UnityEngine.SubsystemsModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.TerrainModule">
            <HintPath>$(ReferencePath)UnityEngine.TerrainModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.TerrainPhysicsModule">
            <HintPath>$(ReferencePath)UnityEngine.TerrainPhysicsModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.TextCoreFontEngineModule">
            <HintPath>$(ReferencePath)UnityEngine.TextCoreFontEngineModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.TextCoreTextEngineModule">
            <HintPath>$(ReferencePath)UnityEngine.TextCoreTextEngineModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.TextRenderingModule">
            <HintPath>$(ReferencePath)UnityEngine.TextRenderingModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.TilemapModule">
            <HintPath>$(ReferencePath)UnityEngine.TilemapModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.TLSModule">
            <HintPath>$(ReferencePath)UnityEngine.TLSModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UI">
            <HintPath>$(ReferencePath)UnityEngine.UI.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UIElementsModule">
            <HintPath>$(ReferencePath)UnityEngine.UIElementsModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UIModule">
            <HintPath>$(ReferencePath)UnityEngine.UIModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UmbraModule">
            <HintPath>$(ReferencePath)UnityEngine.UmbraModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UnityAnalyticsCommonModule">
            <HintPath>$(ReferencePath)UnityEngine.UnityAnalyticsCommonModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UnityAnalyticsModule">
            <HintPath>$(ReferencePath)UnityEngine.UnityAnalyticsModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UnityConnectModule">
            <HintPath>$(ReferencePath)UnityEngine.UnityConnectModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UnityCurlModule">
            <HintPath>$(ReferencePath)UnityEngine.UnityCurlModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UnityTestProtocolModule">
            <HintPath>$(ReferencePath)UnityEngine.UnityTestProtocolModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UnityWebRequestAssetBundleModule">
            <HintPath>$(ReferencePath)UnityEngine.UnityWebRequestAssetBundleModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UnityWebRequestAudioModule">
            <HintPath>$(ReferencePath)UnityEngine.UnityWebRequestAudioModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UnityWebRequestModule">
            <HintPath>$(ReferencePath)UnityEngine.UnityWebRequestModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UnityWebRequestTextureModule">
            <HintPath>$(ReferencePath)UnityEngine.UnityWebRequestTextureModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UnityWebRequestWWWModule">
            <HintPath>$(ReferencePath)UnityEngine.UnityWebRequestWWWModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.VehiclesModule">
            <HintPath>$(ReferencePath)UnityEngine.VehiclesModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.VFXModule">
            <HintPath>$(ReferencePath)UnityEngine.VFXModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.VideoModule">
            <HintPath>$(ReferencePath)UnityEngine.VideoModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.VRModule">
            <HintPath>$(ReferencePath)UnityEngine.VRModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.WindModule">
            <HintPath>$(ReferencePath)UnityEngine.WindModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.XRModule">
            <HintPath>$(ReferencePath)UnityEngine.XRModule.dll</HintPath>
        </Reference>
    </ItemGroup>
    <Choose>
        <When Condition=" '$(Configuration)' == 'IL2CPP_MELONLOADER_PRE57'">
            <ItemGroup>
                <Reference Include="UnhollowerBaseLib">
                    <HintPath>$(ReferencePath)UnhollowerBaseLib.dll</HintPath>
                </Reference>
                <Reference Include="UnhollowerRuntimeLib">
                    <HintPath>$(ReferencePath)UnhollowerRuntimeLib.dll</HintPath>
                </Reference>
                <Reference Include="Il2Cppmscorlib">
                    <HintPath>$(ReferencePath)Il2Cppmscorlib.dll</HintPath>
                </Reference>
                <Reference Include="MelonLoader">
                    <HintPath>$(ReferencePath)MelonLoader.dll</HintPath>
                </Reference>
            </ItemGroup>
        </When>
        <When Condition=" '$(Configuration)' == 'IL2CPP_MELONLOADER'">
            <ItemGroup>
                <Reference Include="Il2Cppmscorlib">
                    <HintPath>$(ReferencePath)Il2Cppmscorlib.dll</HintPath>
                </Reference>
                <Reference Include="MelonLoader">
                    <HintPath>$(ReferencePath)MelonLoader.dll</HintPath>
                </Reference>
                <Reference Include="Il2CppInterop.Runtime">
                    <HintPath>$(ReferencePath)Il2CppInterop.Runtime.dll</HintPath>
                </Reference>
            </ItemGroup>
        </When>
        <When Condition=" '$(Configuration)' == 'IL2CPP_BEPINEX' ">
            <ItemGroup>
                <Reference Include="Il2Cppmscorlib">
                    <HintPath>$(ReferencePath)Il2Cppmscorlib.dll</HintPath>
                </Reference>
            </ItemGroup>
        </When>
    </Choose>
    <ItemGroup Condition=" '$(Configuration)' == 'IL2CPP_BEPINEX' ">
        <Reference Include="BepInEx.Core">
            <HintPath>$(ReferencePath)\BepInEx.Core.dll</HintPath>
        </Reference>
        <Reference Include="BepInEx.Preloader.Core">
            <HintPath>$(ReferencePath)\BepInEx.Preloader.Core.dll</HintPath>
        </Reference>
        <Reference Include="BepInEx.Unity.Common">
            <HintPath>$(ReferencePath)\BepInEx.Unity.Common.dll</HintPath>
        </Reference>
        <Reference Include="BepInEx.Unity.IL2CPP">
            <HintPath>$(ReferencePath)\BepInEx.Unity.IL2CPP.dll</HintPath>
        </Reference>
        <Reference Include="Il2CppInterop.Common">
            <HintPath>$(ReferencePath)\Il2CppInterop.Common.dll</HintPath>
        </Reference>
        <Reference Include="Il2CppInterop.Generator">
            <HintPath>$(ReferencePath)\Il2CppInterop.Generator.dll</HintPath>
        </Reference>
        <Reference Include="Il2CppInterop.HarmonySupport">
            <HintPath>$(ReferencePath)\Il2CppInterop.HarmonySupport.dll</HintPath>
        </Reference>
        <Reference Include="Il2CppInterop.Runtime">
            <HintPath>$(ReferencePath)\Il2CppInterop.Runtime.dll</HintPath>
        </Reference>
    </ItemGroup>
</Project>
