name: Build C# Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: windows-latest
    if: github.event_name != 'schedule'
    strategy:
      matrix:
        configuration: [IL2CPP_Melonloader, IL2CPP_BepInEx, Mono_Melonloader, Mono_BepInEx]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet packages
        run: nuget restore shadcnui.sln

      - name: Build ${{ matrix.configuration }}
        run: msbuild shadcnui.sln /p:Configuration=${{ matrix.configuration }} /p:Platform="Any CPU" /m

      - name: Upload shadcnui.dll
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: shadcnui-build-${{ matrix.configuration }}
          path: shadcnui/bin/${{ matrix.configuration }}/shadcnui.dll
          if-no-files-found: error
          retention-days: 30

      - name: Upload shadcnui_Demo.dll
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: shadcnui_Demo-build-${{ matrix.configuration }}
          path: shadcnui_Demo/bin/${{ matrix.configuration }}/netstandard2.1/shadcnui_Demo.dll
          if-no-files-found: error
          retention-days: 30

  release:
    needs: build
    runs-on: windows-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    strategy:
      matrix:
        configuration: [IL2CPP_Melonloader, IL2CPP_BepInEx, Mono_Melonloader, Mono_BepInEx]

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Upload DLLs to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $release_url = "${{ github.event.release.upload_url }}"
          $config = "${{ matrix.configuration }}"
          
          $dll_path = "./artifacts/shadcnui-build-$config/shadcnui.dll"
          $testing_dll_path = "./artifacts/shadcnui_Demo-build-$config/shadcnui_Demo.dll"
          
          if (Test-Path $dll_path) {
            gh release upload ${{ github.event.release.tag_name }} "$dll_path#shadcnui-$config.dll" --clobber
          }
          
          if (Test-Path $testing_dll_path) {
            gh release upload ${{ github.event.release.tag_name }} "$testing_dll_path#shadcnui_Demo-$config.dll" --clobber
          }

  nightly_build:
    runs-on: windows-latest
    if: github.event_name == 'schedule'
    strategy:
      matrix:
        configuration: [IL2CPP_Melonloader, IL2CPP_BepInEx, Mono_Melonloader, Mono_BepInEx]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet packages
        run: nuget restore shadcnui.sln

      - name: Build ${{ matrix.configuration }} (Nightly)
        run: msbuild shadcnui.sln /p:Configuration=${{ matrix.configuration }} /p:Platform="Any CPU" /m

      - name: Upload shadcnui.dll
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: shadcnui-nightly-${{ github.run_number }}-${{ matrix.configuration }}
          path: shadcnui/bin/${{ matrix.configuration }}/shadcnui.dll
          if-no-files-found: error
          retention-days: 14

      - name: Upload shadcnui_Demo.dll
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: shadcnui_Demo-nightly-${{ github.run_number }}-${{ matrix.configuration }}
          path: shadcnui_Demo/bin/${{ matrix.configuration }}/netstandard2.1/shadcnui_Demo.dll
          if-no-files-found: error
          retention-days: 14